// Mocks generated by Mockito 5.4.6 from annotations
// in tazakar/test/sprint_3_9_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tazakar/features/nlu/application/parse_voice_input_use_case.dart'
    as _i3;
import 'package:tazakar/features/nlu/domain/entities/parsed_intent.dart' as _i2;
import 'package:tazakar/infrastructure/platform/ai_channel.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeParsedIntent_0 extends _i1.SmartFake implements _i2.ParsedIntent {
  _FakeParsedIntent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ParseVoiceInputUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockParseVoiceInputUseCase extends _i1.Mock
    implements _i3.ParseVoiceInputUseCase {
  MockParseVoiceInputUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ParsedIntent> execute(
    String? transcript, {
    _i2.DialectCode? dialectHint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #execute,
              [transcript],
              {#dialectHint: dialectHint},
            ),
            returnValue: _i4.Future<_i2.ParsedIntent>.value(
              _FakeParsedIntent_0(
                this,
                Invocation.method(
                  #execute,
                  [transcript],
                  {#dialectHint: dialectHint},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ParsedIntent>);
}

/// A class which mocks [AiChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiChannel extends _i1.Mock implements _i5.AiChannel {
  MockAiChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> loadModel() =>
      (super.noSuchMethod(
            Invocation.method(#loadModel, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isModelLoaded() =>
      (super.noSuchMethod(
            Invocation.method(#isModelLoaded, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> transcribeAudio(_i6.Uint8List? audioBytes) =>
      (super.noSuchMethod(
            Invocation.method(#transcribeAudio, [audioBytes]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> startRecording() =>
      (super.noSuchMethod(
            Invocation.method(#startRecording, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i6.Uint8List?> stopRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopRecording, []),
            returnValue: _i4.Future<_i6.Uint8List?>.value(),
          )
          as _i4.Future<_i6.Uint8List?>);

  @override
  _i4.Future<String?> recordAndTranscribe() =>
      (super.noSuchMethod(
            Invocation.method(#recordAndTranscribe, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
